#!/bin/sh

set -e

echo "Creating user"
psql -q -c "DROP ROLE IF EXISTS \"$POSTGRES_USERNAME\";"
psql -q <<-EOF
    CREATE ROLE "$POSTGRES_USERNAME" WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
    ALTER ROLE "$POSTGRES_USERNAME" WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
    ALTER ROLE "$POSTGRES_USERNAME" WITH SUPERUSER;
    ALTER ROLE "$POSTGRES_USERNAME" WITH LOGIN;
EOF

echo "Creating database"
psql -q <<-EOF
    CREATE DATABASE "$DB" WITH OWNER="$POSTGRES_USERNAME" ENCODING='UTF8';
    GRANT ALL ON DATABASE "$DB" TO "$POSTGRES_USERNAME"
EOF